config/routes.rb
TienDataBackend::Application.routes.draw do
  get '/health', to: 'health#status'
  
  resources :stores do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :store
  
  validates :comment, presence: true
  validates :store, presence: true
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :comments, dependent: :destroy
  
  validates :name, presence: true
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, allow_blank: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @store = Store.find(params[:store_id])
    @comment = @store.comments.create(comment_params)
    redirect_to store_path(@store)
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/health_controller.rb
class HealthController < ApplicationController
  def status
    render json: {
      status: 'OK',
      rails_version: Rails.version,
      timestamp: Time.current,
      database_connected: database_connected?
    }
  end

  private

  def database_connected?
    ActiveRecord::Base.connection.execute('SELECT 1')
    true
  rescue StandardError => e
    false
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @stores }
    end
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @store = Store.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/new
  # GET /stores/new.json
  def new
    @store = Store.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @store }
    end
  end

  # GET /stores/1/edit
  def edit
    @store = Store.find(params[:id])
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render json: @store, status: :created, location: @store }
      else
        format.html { render action: "new" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /stores/1
  # PUT /stores/1.json
  def update
    @store = Store.find(params[:id])

    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def store_params
    params.require(:store).permit(:name, :address, :phone, :email, :URL, :hoursOfOperation)
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    @store.destroy

    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TienDataBackend</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :URL %><br />
    <%= f.text_field :URL %>
  </div>
  <div class="field">
    <%= f.label :hoursOfOperation %><br />
    <%= f.text_field :hoursOfOperation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<h1>Listing stores</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Url</th>
    <th>Hoursofoperation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stores.each do |store| %>
  <tr>
    <td><%= store.name %></td>
    <td><%= store.address %></td>
    <td><%= store.phone %></td>
    <td><%= store.email %></td>
    <td><%= store.URL %></td>
    <td><%= store.hoursOfOperation %></td>
    <td><%= link_to 'Show', store %></td>
    <td><%= link_to 'Edit', edit_store_path(store) %></td>
    <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Store', new_store_path %>

app/views/stores/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @store.name %>
</p>

<p>
  <b>Address:</b>
  <%= @store.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @store.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @store.email %>
</p>

<p>
  <b>Url:</b>
  <%= @store.URL %>
</p>

<p>
  <b>Hoursofoperation:</b>
  <%= @store.hoursOfOperation %>
</p>

<h2>Add a comment:</h2>
<%= form_for([@store, @store.comments.build]) do |f| %>
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>